# Generated by Django 5.0 on 2023-12-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_nucleitrigger_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=' ', max_length=50, verbose_name='Почта'),
        ),
    ]
