# Generated by Django 5.0 on 2024-03-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comment_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.TextField(default=' ', verbose_name='IP')),
                ('port', models.TextField(default=' ', verbose_name='port')),
                ('logins', models.TextField(default=' ', max_length=1000000000, verbose_name='Логины')),
                ('passwords', models.TextField(default=' ', max_length=100000000, verbose_name='Пароли')),
                ('key', models.TextField(default=' ', max_length=250, verbose_name='Ключ подписиси jwt')),
                ('expiretime', models.TextField(default=' ', max_length=100, verbose_name='Время жизни в секундах')),
                ('csrf_name', models.TextField(default=' ', max_length=100, verbose_name='csrf token name')),
                ('csrf_param_name', models.TextField(default=' ', max_length=100, verbose_name='csrf param name')),
                ('auth_token_type', models.TextField(default=' ', max_length=100, verbose_name='auth token type')),
                ('auth_token_name', models.TextField(default=' ', max_length=100, verbose_name='auth token name')),
                ('auth_type', models.TextField(default=' ', max_length=100, verbose_name='auth type')),
                ('token_refresh_end', models.TextField(default=' ', max_length=100, verbose_name='token refresh end')),
                ('Scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fullscan')),
            ],
            options={
                'verbose_name': 'Proxy config',
                'verbose_name_plural': 'Proxy configs',
            },
        ),
    ]
