# Generated by Django 5.0 on 2024-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_proxyconfig_auth_request_proxyconfig_login_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='period_status',
            field=models.TextField(default=' ', max_length=100000, verbose_name='period status'),
        ),
    ]
